name: powerplantmatching
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - entsoe-py
  - geopy
  - ipython
  - matplotlib
  - networkx>=1.10
  - numpy
  - pandas>=0.23.0
  - pycountry>=19.8.18
  - python=3
  - pyyaml>=5.1.0
  - quilt
  - requests
  - scipy
  - seaborn
  - six
  - xlrd
